server:
  port: 8880

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/faro-blog?useUnicode=true&characterEncoding=utf-8
    username: faro-blog
    password: faro-blog
    driver-class-name: com.mysql.cj.jdbc.Driver


# 整合Mybatis
mybatis:
  # ** 表示在mapper下不管有多少文件夹，都可以全部识别
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: blog.pojo
  #  打印sql相关的日志信息
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
